# Generated by Django 5.1.15 on 2026-02-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        ("predictions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(unique=True)),
                ("matches_played", models.IntegerField(default=0)),
                ("total_goals", models.IntegerField(default=0)),
                ("home_wins", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("away_wins", models.IntegerField(default=0)),
                ("predictions_made", models.IntegerField(default=0)),
                ("predictions_correct", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Daily Stats",
                "verbose_name_plural": "Daily Stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_predictions", models.IntegerField(default=0)),
                ("correct_predictions", models.IntegerField(default=0)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("home_predictions", models.IntegerField(default=0)),
                ("home_correct", models.IntegerField(default=0)),
                ("draw_predictions", models.IntegerField(default=0)),
                ("draw_correct", models.IntegerField(default=0)),
                ("away_predictions", models.IntegerField(default=0)),
                ("away_correct", models.IntegerField(default=0)),
                (
                    "log_loss",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "brier_score",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("high_confidence_predictions", models.IntegerField(default=0)),
                ("high_confidence_correct", models.IntegerField(default=0)),
                ("medium_confidence_predictions", models.IntegerField(default=0)),
                ("medium_confidence_correct", models.IntegerField(default=0)),
                ("low_confidence_predictions", models.IntegerField(default=0)),
                ("low_confidence_correct", models.IntegerField(default=0)),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_metrics",
                        to="leagues.league",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="predictions.modelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Metrics",
                "verbose_name_plural": "Model Metrics",
                "ordering": ["-period_end"],
            },
        ),
    ]
