# Generated by Django 5.1.15 on 2026-02-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Football-Data.co.uk code (e.g., E0, SP1)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "tier",
                    models.IntegerField(
                        choices=[
                            (1, "Tier 1 - Top 5 Leagues"),
                            (2, "Tier 2 - Other Major"),
                            (3, "Tier 3 - Second Divisions"),
                            (4, "Tier 4 - Other"),
                        ],
                        default=2,
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Lower = higher priority"
                    ),
                ),
                (
                    "season_start_month",
                    models.IntegerField(
                        default=8, help_text="Month when season starts (1-12)"
                    ),
                ),
                (
                    "season_end_month",
                    models.IntegerField(
                        default=5, help_text="Month when season ends (1-12)"
                    ),
                ),
                (
                    "has_xg_data",
                    models.BooleanField(
                        default=False, help_text="Whether xG data is available"
                    ),
                ),
                (
                    "has_player_data",
                    models.BooleanField(
                        default=False,
                        help_text="Whether player-level data is available",
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "ordering": ["tier", "priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                (
                    "code",
                    models.CharField(
                        help_text="Season code (e.g., '2324')", max_length=10
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., '2023-24')", max_length=20
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("total_matches", models.IntegerField(default=0)),
                ("matches_played", models.IntegerField(default=0)),
                ("total_goals", models.IntegerField(default=0)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "ordering": ["-code"],
                "unique_together": {("league", "code")},
            },
        ),
    ]
