# Generated by Django 5.1.15 on 2026-02-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Short code (e.g., ARS, MUN)",
                        max_length=10,
                    ),
                ),
                (
                    "fd_name",
                    models.CharField(
                        blank=True,
                        help_text="Name in Football-Data.co.uk",
                        max_length=200,
                    ),
                ),
                (
                    "fbref_id",
                    models.CharField(
                        blank=True, help_text="FBref team ID", max_length=50
                    ),
                ),
                (
                    "understat_id",
                    models.CharField(
                        blank=True, help_text="Understat team ID", max_length=50
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("founded", models.IntegerField(blank=True, null=True)),
                ("stadium", models.CharField(blank=True, max_length=200)),
                ("stadium_capacity", models.IntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HeadToHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                ("total_matches", models.IntegerField(default=0)),
                ("team_a_wins", models.IntegerField(default=0)),
                ("team_b_wins", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("team_a_goals", models.IntegerField(default=0)),
                ("team_b_goals", models.IntegerField(default=0)),
                ("matches_at_a", models.IntegerField(default=0)),
                ("team_a_home_wins", models.IntegerField(default=0)),
                ("team_b_away_wins", models.IntegerField(default=0)),
                ("draws_at_a", models.IntegerField(default=0)),
                ("matches_at_b", models.IntegerField(default=0)),
                ("team_b_home_wins", models.IntegerField(default=0)),
                ("team_a_away_wins", models.IntegerField(default=0)),
                ("draws_at_b", models.IntegerField(default=0)),
                ("last_match_date", models.DateField(blank=True, null=True)),
                (
                    "team_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="h2h_as_team_a",
                        to="teams.team",
                    ),
                ),
                (
                    "team_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="h2h_as_team_b",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Head to Head",
                "verbose_name_plural": "Head to Head Records",
                "unique_together": {("team_a", "team_b")},
            },
        ),
        migrations.CreateModel(
            name="TeamSeasonStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                ("matches_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("goals_for", models.IntegerField(default=0)),
                ("goals_against", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("league_position", models.IntegerField(blank=True, null=True)),
                ("previous_position", models.IntegerField(blank=True, null=True)),
                (
                    "form",
                    models.CharField(
                        blank=True, help_text="e.g., WWDLW", max_length=10
                    ),
                ),
                ("home_played", models.IntegerField(default=0)),
                ("home_wins", models.IntegerField(default=0)),
                ("home_draws", models.IntegerField(default=0)),
                ("home_losses", models.IntegerField(default=0)),
                ("home_goals_for", models.IntegerField(default=0)),
                ("home_goals_against", models.IntegerField(default=0)),
                ("away_played", models.IntegerField(default=0)),
                ("away_wins", models.IntegerField(default=0)),
                ("away_draws", models.IntegerField(default=0)),
                ("away_losses", models.IntegerField(default=0)),
                ("away_goals_for", models.IntegerField(default=0)),
                ("away_goals_against", models.IntegerField(default=0)),
                (
                    "xg_for",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "xg_against",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("clean_sheets", models.IntegerField(default=0)),
                ("failed_to_score", models.IntegerField(default=0)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_stats",
                        to="leagues.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_stats",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Season Stats",
                "verbose_name_plural": "Team Season Stats",
                "ordering": ["league_position"],
                "unique_together": {("team", "season")},
            },
        ),
    ]
