# Generated by Django 5.1.15 on 2026-09-30 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_teaminjury"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name exactly as the provider sent it", max_length=200
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "key",
                    models.CharField(
                        help_text="identity.canonical_key(name, country)",
                        max_length=200,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="e.g. football-data.co.uk", max_length=40
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Alias",
                "verbose_name_plural": "Team Aliases",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "key"), name="unique_team_alias_per_country"
                    )
                ],
            },
        ),
    ]
