# Generated by Django 5.1.15 on 2026-07-31 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamInjury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                ("player_name", models.CharField(max_length=200)),
                (
                    "injury_type",
                    models.CharField(
                        blank=True, help_text="e.g. 'Missing Fixture'", max_length=100
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "as_of_date",
                    models.DateField(
                        help_text="Date this record was reported/captured"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injuries",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Injury",
                "verbose_name_plural": "Team Injuries",
                "ordering": ["-as_of_date"],
                "indexes": [
                    models.Index(
                        fields=["team", "as_of_date"],
                        name="teams_teami_team_id_a46f65_idx",
                    )
                ],
            },
        ),
    ]
