# Generated by Django 5.1.15 on 2026-02-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0001_initial"),
        ("matches", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("season", "home_team", "away_team", "match_date"),
                name="unique_match_per_season",
            ),
        ),
    ]
