# Generated by Django 5.1.15 on 2026-09-30 12:12

from django.db import migrations, models


def backfill_kickoff_at(apps, schema_editor):
    """
    kickoff_time was stored in the provider's own clock: UTC for
    football-data.org rows (fd_match_id 'fdorg_...'), UK local time for
    football-data.co.uk rows. Convert both to one UTC instant.
    """
    from datetime import datetime, timezone
    from zoneinfo import ZoneInfo

    Match = apps.get_model('matches', 'Match')
    london = ZoneInfo('Europe/London')
    batch = []
    qs = Match.objects.filter(kickoff_time__isnull=False, kickoff_at__isnull=True).only(
        'id', 'match_date', 'kickoff_time', 'fd_match_id')
    for m in qs.iterator(chunk_size=2000):
        naive = datetime.combine(m.match_date, m.kickoff_time)
        if (m.fd_match_id or '').startswith('fdorg_'):
            m.kickoff_at = naive.replace(tzinfo=timezone.utc)
        else:
            m.kickoff_at = naive.replace(tzinfo=london).astimezone(timezone.utc)
        batch.append(m)
        if len(batch) >= 2000:
            Match.objects.bulk_update(batch, ['kickoff_at'])
            batch = []
    if batch:
        Match.objects.bulk_update(batch, ['kickoff_at'])


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_add_unique_constraint_on_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="kickoff_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_kickoff_at, migrations.RunPython.noop),
    ]
