# Generated by Django 5.1.15 on 2026-02-18 10:39

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        ("predictions", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Document Categories",
                "db_table": "document_categories",
            },
        ),
        migrations.CreateModel(
            name="EmbeddingCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "embedding_cache",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("betting_guide", "Betting Guide"),
                            ("team_analysis", "Team Analysis"),
                            ("strategy", "Strategy Document"),
                            ("match_preview", "Match Preview"),
                            ("statistics", "Statistics Report"),
                            ("news", "News Article"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "leagues",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="leagues.league"
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="teams.team"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentcategory",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("chunk_index", models.PositiveIntegerField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI (GPT)"),
                            ("anthropic", "Anthropic (Claude)"),
                            ("google", "Google (Gemini)"),
                        ],
                        default="openai",
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("response", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("context_summary", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("confidence_assessment", models.TextField(blank=True)),
                ("risk_analysis", models.TextField(blank=True)),
                ("key_factors", models.JSONField(blank=True, default=list)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="predictions.prediction",
                    ),
                ),
                (
                    "context_chunks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommendations",
                        to="documents.documentchunk",
                    ),
                ),
            ],
            options={
                "db_table": "ai_recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="documents_documen_fc21d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_active"], name="documents_is_acti_a803bb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
