# Generated by Django 5.1.15 on 2026-07-31 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("teams", "0002_teaminjury"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamNewsSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "as_of_date",
                    models.DateField(help_text="Date this signal was generated"),
                ),
                ("injury_mention_score", models.FloatField(default=0.0)),
                ("sentiment_score", models.FloatField(default=0.0)),
                (
                    "source_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of news articles this signal was derived from",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, help_text="LLM provider used", max_length=20
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_signals",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_news_signals",
                "ordering": ["-as_of_date"],
                "indexes": [
                    models.Index(
                        fields=["team", "as_of_date"],
                        name="team_news_s_team_id_c61d4e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "as_of_date"), name="unique_team_signal_per_day"
                    )
                ],
            },
        ),
    ]
