# Generated by Django 5.1.15 on 2026-02-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                ("match_date", models.DateField()),
                ("kickoff_time", models.TimeField(blank=True, null=True)),
                ("matchweek", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("halftime", "Half Time"),
                            ("finished", "Finished"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                ("home_halftime_score", models.IntegerField(blank=True, null=True)),
                ("away_halftime_score", models.IntegerField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[("H", "Home Win"), ("D", "Draw"), ("A", "Away Win")],
                        max_length=1,
                    ),
                ),
                (
                    "fd_match_id",
                    models.CharField(
                        blank=True,
                        help_text="Football-Data.co.uk match ID",
                        max_length=50,
                    ),
                ),
                ("fbref_match_id", models.CharField(blank=True, max_length=50)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="leagues.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-match_date", "-kickoff_time"],
            },
        ),
        migrations.CreateModel(
            name="MatchOdds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                (
                    "home_odds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "draw_odds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "away_odds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "over_25_odds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "under_25_odds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "btts_yes_odds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "btts_no_odds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "bookmaker",
                    models.CharField(
                        default="Average", help_text="Source of odds", max_length=50
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Odds",
                "verbose_name_plural": "Match Odds",
            },
        ),
        migrations.CreateModel(
            name="MatchStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_source", models.CharField(blank=True, max_length=50)),
                (
                    "possession_home",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "possession_away",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("shots_home", models.IntegerField(blank=True, null=True)),
                ("shots_away", models.IntegerField(blank=True, null=True)),
                ("shots_on_target_home", models.IntegerField(blank=True, null=True)),
                ("shots_on_target_away", models.IntegerField(blank=True, null=True)),
                ("corners_home", models.IntegerField(blank=True, null=True)),
                ("corners_away", models.IntegerField(blank=True, null=True)),
                ("fouls_home", models.IntegerField(blank=True, null=True)),
                ("fouls_away", models.IntegerField(blank=True, null=True)),
                ("yellow_cards_home", models.IntegerField(blank=True, null=True)),
                ("yellow_cards_away", models.IntegerField(blank=True, null=True)),
                ("red_cards_home", models.IntegerField(blank=True, null=True)),
                ("red_cards_away", models.IntegerField(blank=True, null=True)),
                (
                    "xg_home",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "xg_away",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Statistics",
                "verbose_name_plural": "Match Statistics",
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["match_date"], name="matches_mat_match_d_8426a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["status"], name="matches_mat_status_a896a5_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["season", "match_date"], name="matches_mat_season__eea137_idx"
            ),
        ),
    ]
